version: '3'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    container_name: sql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrong@Passw0rd"
    volumes:
      - ./sql/data/data:/var/opt/mssql/data
      - ./sql/data/log:/var/opt/mssql/log
      - ./sql/data/secrets:/var/opt/mssql/secrets
      - ./sql/scripts:/usr/src/app 
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    networks:
      alfatz:
        ipv4_address: 192.168.172.2

  api:
    build: ./webapi
    restart: always
    container_name: api
    depends_on:
      - sql
    ports:
      - 5000:5000
    networks:
      alfatz:
        ipv4_address: 192.168.172.3

networks:
  alfatz:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.172.0/24
