version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrong@Passw0rd"
    volumes:
      - ./sql/data/data:/var/opt/mssql/data
      - ./sql/data/log:/var/opt/mssql/log
      - ./sql/data/secrets:/var/opt/mssql/secrets
      - ./sql/scripts:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    networks:
      alfanet:
        ipv4_address: 192.168.172.2

  alfaapi:
    build: ./alfaapi
    restart: always
    depends_on:
      - sqlserver
    ports:
      - 5000:5000
    networks:
      alfanet:
        ipv4_address: 192.168.172.3

  alfafront:
    build: ./alfafront
    restart: always
    depends_on:
      - alfaapi
    ports:
      - 8000:80
    networks:
      alfanet:
        ipv4_address: 192.168.172.4

networks:
  alfanet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.172.0/24
